import { readFileSync, writeFileSync } from 'fs'

function q(s) { return "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'" }
function qa(arr) { return '[' + arr.map(q).join(', ') + ']' }

function entry(o) {
  let lines = ['  {']
  for (const [k, v] of Object.entries(o)) {
    if (v === undefined || v === null || v === '') continue
    let val
    if (Array.isArray(v)) {
      if (typeof v[0] === 'string') {
        val = qa(v)
      } else {
        val = '[' + v.map(ex => {
          let s = '{'
          if (ex.title) s += 'title: ' + q(ex.title) + ', '
          s += 'code: ' + q(ex.code) + '}'
          return s
        }).join(', ') + ']'
      }
    } else if (typeof v === 'string') {
      val = q(v)
    } else {
      val = String(v)
    }
    lines.push('    ' + k + ': ' + val + ',')
  }
  let last = lines.pop()
  lines.push(last.replace(/,$/, ''))
  lines.push('  }')
  return lines.join('\n')
}

const entries = [
  // === Python ===
  { id: 'py_list', name: 'list', category: '内置类型', language: 'python', full_name: 'list', signature: 'list([iterable])', signatures: ['list([iterable])'], description: '可变序列，可存放任意类型元素。动态数组，尾部插入 O(1)，中间插入 O(n)。', example: 'lst = [1, 2, 3]\nlst.append(4)\nlst.pop()', examples: [{ title: '推导式', code: 'squares = [x*x for x in range(10)]\neven = [x for x in lst if x % 2 == 0]' }, { title: '常用方法', code: 'lst = [3,1,2]\nlst.sort()\nlst.reverse()\nlst.append(4)\nlst.pop()\nlst.insert(0, 0)\nlst.remove(1)\nlst.count(2)\nlst.index(3)' }], complexity: '索引 O(1), append 均摊 O(1), 插入/删除 O(n)', notes: 'list.sort() 原地排序（Timsort，稳定），sorted(lst) 返回新列表。', leetcode_tips: 'list comprehension 比手动 for 循环快。sort(key=...) 自定义排序键。', see_also: ['tuple', 'deque_py', 'py_range'] },
  { id: 'py_dict', name: 'dict', category: '内置类型', language: 'python', full_name: 'dict', signature: 'dict(**kwargs) / dict(iterable) / {key: value}', signatures: ['dict(**kwargs)', 'dict(iterable)', '{key: value}'], description: '字典，键值对映射。Python 3.7+ 保持插入顺序。平均 O(1) 操作。', example: 'd = {"a": 1, "b": 2}\nd.get("a")\nd["c"] = 3', examples: [{ title: '计数', code: 'd = {}\nfor c in s:\n  d[c] = d.get(c, 0) + 1\n# or use collections.Counter' }, { title: '字典推导', code: 'squares = {x: x*x for x in range(5)}\n# {0:0, 1:1, 2:4, 3:9, 4:16}' }], complexity: '平均 O(1)', notes: 'Python 3.6 起 dict 使用紧凑表示节省内存。keys()/values()/items() 返回视图。', leetcode_tips: '哈希表计数、缓存中间结果。setdefault 方法可简化初始化。', see_also: ['defaultdict', 'counter', 'py_set'] },
  { id: 'py_set', name: 'set', category: '内置类型', language: 'python', full_name: 'set', signature: 'set([iterable])', signatures: ['set([iterable])'], description: '无序集合，元素唯一。平均 O(1) 成员检测。支持 & | - ^ 运算。', example: 's = {1, 2, 3}\ns.add(4)\ns.remove(2)', examples: [{ title: '集合运算', code: 'a = {1,2,3}\nb = {2,3,4}\na & b  # {2,3} 交集\na | b  # {1,2,3,4} 并集\na - b  # {1} 差集\na ^ b  # {1,4} 对称差' }, { title: '去重', code: 'unique = list(set([1,2,2,3]))\n# [1,2,3] 注意顺序不保证' }], complexity: '平均 O(1)', notes: '元素必须可哈希（hashable）。frozenset 是不可变版本。', leetcode_tips: '快速去重、成员检查、集合运算（如共同好友）。', see_also: ['py_list', 'py_dict', 'counter'] },
  { id: 'py_str', name: 'str', category: '内置类型', language: 'python', full_name: 'str', signature: 'str(object="")', signatures: ['str(object="")'], description: '不可变的 Unicode 字符串序列。支持切片、查找、替换等丰富操作。', example: 's = "hello"\ns.upper()\ns[0:3]\ns.find("ll")', examples: [{ title: '常用方法', code: 's = "LeetCode"\ns.lower()\ns.upper()\ns.isdigit()\ns.isalpha()\ns.split(",")\ns.join(["a","b"])\ns.strip()\ns.replace("e", "a")\ns.startswith("Lee")\ns.count("e")' }, { title: '切片与反转', code: 's = "abcdef"\ns[::-1]  # "fedcba" 反转\ns[::2]   # "ace" 隔一取一\ns[1:4]   # "bcd"' }], complexity: '索引 O(1), 查找 O(n), 切片 O(k)', notes: '字符串不可变，所有方法返回新字符串。join 比 + 拼接更高效。', leetcode_tips: 's[::-1] 反转字符串。split/join 处理单词拆分。切片左闭右开。', see_also: ['py_list', 'tuple', 'enumerate_zip'] },
  { id: 'py_tuple', name: 'tuple', category: '内置类型', language: 'python', full_name: 'tuple', signature: 'tuple([iterable])', signatures: ['tuple([iterable])'], description: '不可变序列，可包含任意类型。适合作为字典键或打包多个返回值。', example: 't = (1, 2, 3)\na, b, c = t\nx, y = y, x  # swap via tuple', examples: [{ title: '解包', code: 'point = (10, 20)\nx, y = point\n# 函数多返回值\ndef min_max(lst):\n  return min(lst), max(lst)' }], complexity: '索引 O(1)', notes: '单元素元组需加逗号: (1,)。namedtuple 给元组元素命名。', leetcode_tips: '用作哈希表的键（如 (i,j) 坐标）。多个返回值打包。', see_also: ['py_list', 'py_str', 'namedtuple'] },
  { id: 'py_range', name: 'range', category: '内置类型', language: 'python', full_name: 'range', signature: 'range(stop) / range(start, stop, step)', signatures: ['range(stop)', 'range(start, stop, step)'], description: '不可变数值序列，延迟计算（不一次性生成所有值）。内存友好。', example: 'for i in range(10): ...\nlist(range(0, 10, 2))  # [0,2,4,6,8]', examples: [{ title: '反向遍历', code: 'for i in range(10, 0, -1):\n  print(i)\n# 10, 9, 8, ..., 1' }], complexity: 'O(1) 生成, O(n) 遍历', notes: 'range 是惰性的，适合大数据范围。in 操作也是 O(1)。', leetcode_tips: '倒序遍历 range(n-1, -1, -1)。range(len(arr)) 不如 enumerate。', see_also: ['py_list', 'enumerate_zip'] },
  { id: 'enumerate_zip', name: 'enumerate / zip', category: '内置函数', language: 'python', full_name: 'enumerate / zip', signature: 'enumerate(iterable, start=0) / zip(*iterables)', signatures: ['enumerate(iterable, start=0)', 'zip(*iterables)'], description: 'enumerate 返回索引-元素对。zip 并行聚合多个可迭代对象。', example: 'for i, char in enumerate("abc"):\n  print(i, char)', examples: [{ title: 'enumerate', code: 'for idx, val in enumerate(["a","b","c"], start=1):\n  print(idx, val)' }, { title: 'zip', code: 'keys = ["a","b","c"]\nvals = [1,2,3]\nd = dict(zip(keys, vals))\n# {"a":1, "b":2, "c":3}\nfor k, v in zip(keys, vals): ...' }], returns: '迭代器', complexity: 'O(1) 返回迭代器, 遍历 O(n)', notes: 'zip 在最短输入耗尽时停止。zip_longest 在 itertools 中。', leetcode_tips: '同时遍历索引和值用 enumerate。同时遍历多个列表用 zip。', see_also: ['py_range', 'map_filter', 'any_all'] },
  { id: 'any_all', name: 'any / all', category: '内置函数', language: 'python', full_name: 'any / all', signature: 'any(iterable) / all(iterable)', signatures: ['any(iterable)', 'all(iterable)'], description: 'any 可迭代对象中任一为真返回 True。all 所有为真返回 True。短路求值。', example: 'any(x > 5 for x in nums)\nall(x > 0 for x in nums)', examples: [{ title: '条件检查', code: 'nums = [1,2,3,4,5]\nhas_even = any(x % 2 == 0 for x in nums)  # True\nall_positive = all(x > 0 for x in nums)    # True' }], returns: 'bool', complexity: '短路，最坏 O(n)', notes: '空可迭代对象：any 返回 False，all 返回 True。', leetcode_tips: '条件判断、边界检查（如棋盘、矩阵的合法性）。', see_also: ['map_filter', 'enumerate_zip'] },
  { id: 'sorted_reversed', name: 'sorted / reversed', category: '内置函数', language: 'python', full_name: 'sorted / reversed', signature: 'sorted(iterable, key=None, reverse=False) / reversed(seq)', signatures: ['sorted(iterable, key=None, reverse=False)', 'reversed(seq)'], description: 'sorted 返回排序后的新列表。reversed 返回反向迭代器。', example: 'sorted([3,1,2])  # [1,2,3]\nlist(reversed([1,2,3]))  # [3,2,1]', examples: [{ title: 'sorted 自定义', code: 'students = [("Alice", 25), ("Bob", 20)]\nsorted_by_age = sorted(students, key=lambda x: x[1])\n# [("Bob",20), ("Alice",25)]' }], returns: 'sorted 返回 list，reversed 返回迭代器', complexity: 'sorted O(n log n), reversed O(1)', notes: 'sorted 返回新列表，不修改原对象。reversed 返回迭代器，需 list() 展开。', leetcode_tips: 'sorted 配合 key 灵活排序。reversed 比 [::-1] 更省内存。', see_also: ['py_list', 'py_range', 'enumerate_zip'] },
  // === Python: collections ===
  { id: 'deque_py', name: 'collections.deque', category: 'collections', language: 'python', full_name: 'collections.deque', signature: 'collections.deque([iterable], maxlen=None)', signatures: ['collections.deque([iterable], maxlen=None)'], description: '双端队列，两端 O(1) 插入/删除。支持 maxlen 限制长度。', example: 'from collections import deque\ndq = deque([1,2,3])\ndq.append(4)\ndq.popleft()', examples: [{ title: '队列', code: 'from collections import deque\nq = deque()\nq.append(1)\nq.popleft()\n# 也可用 q.pop() 和 q.appendleft()' }, { title: '定长滑动窗口', code: 'window = deque(maxlen=3)\nfor x in data:\n  window.append(x)  # 自动移除超出的左端元素' }], complexity: 'O(1) 两端操作', notes: '线程安全的头尾操作。maxlen 超过容量时自动丢弃左端元素。', leetcode_tips: 'BFS 队列、滑动窗口、回文检查。比 list 做队列快（list.pop(0) 是 O(n)）。', see_also: ['py_list', 'defaultdict', 'heapq'] },
  { id: 'defaultdict', name: 'defaultdict', category: 'collections', language: 'python', full_name: 'collections.defaultdict', signature: 'collections.defaultdict(default_factory)', signatures: ['collections.defaultdict(default_factory)'], description: '带默认值的字典。访问不存在的键时，自动调用 default_factory 生成默认值。', example: 'from collections import defaultdict\nd = defaultdict(int)\nd["a"] += 1  # 无需先初始化', examples: [{ title: '计数', code: 'freq = defaultdict(int)\nfor c in s:\n  freq[c] += 1' }, { title: '分组', code: 'groups = defaultdict(list)\nfor name, score in data:\n  groups[name].append(score)' }], complexity: '平均 O(1)', notes: 'default_factory 可以是 int/list/set/dict 等。lambda 可自定义。', leetcode_tips: '分组、计数、邻接表构建时非常方便，避免手动检查键是否存在。', see_also: ['py_dict', 'counter', 'deque_py'] },
  { id: 'counter', name: 'Counter', category: 'collections', language: 'python', full_name: 'collections.Counter', signature: 'collections.Counter([iterable])', signatures: ['collections.Counter([iterable])'], description: '计数哈希表，继承 dict。统计可哈希对象出现次数。', example: 'from collections import Counter\ncnt = Counter("aabbbc")\nprint(cnt["a"])  # 2\nprint(cnt.most_common(2))', examples: [{ title: '常用操作', code: 'cnt = Counter("leetcode")\ncnt["e"]  # 2\ncnt.most_common(2)  # [("e",2), ("l",1)]\nlist(cnt.elements())\ncnt2 = Counter("leet")\ncnt - cnt2  # 差值计数' }], complexity: '构建 O(n)', notes: 'most_common 使用堆排序，O(n log k)。update 可追加计数。subtract 减去计数。', leetcode_tips: '字符/单词频次统计、Anagram 判断、找出出现次数前 k 的元素。', see_also: ['py_dict', 'defaultdict', 'heapq'] },
  { id: 'namedtuple', name: 'namedtuple', category: 'collections', language: 'python', full_name: 'collections.namedtuple', signature: 'namedtuple(typename, field_names)', signatures: ['namedtuple(typename, field_names)'], description: '命名元组工厂函数，创建带字段名的轻量级不可变类。比普通类更省内存。', example: 'from collections import namedtuple\nPoint = namedtuple("Point", ["x", "y"])\np = Point(1, 2)\np.x + p.y', examples: [{ title: '定义与使用', code: 'Student = namedtuple("Student", ["name", "age", "grade"])\ns = Student("Alice", 20, "A")\ns.name  # "Alice"\nname, age, grade = s  # 支持解包' }], returns: 'namedtuple 类', complexity: '', notes: '字段也可通过下标访问（因继承 tuple）。_replace 方法创建新实例。_asdict 转字典。', leetcode_tips: '表示坐标、权重边等不可变数据结构。比 dict 省内存。', see_also: ['py_tuple', 'dataclasses'] },
  // === Python: Algorithms ===
  { id: 'heapq', name: 'heapq', category: '算法', language: 'python', full_name: 'heapq (堆队列)', signature: 'heapq.heappush(heap, item) / heapq.heappop(heap)', signatures: ['heapq.heappush(heap, item)', 'heapq.heappop(heap)', 'heapq.heapify(x)', 'heapq.nlargest(n, iterable)', 'heapq.nsmallest(n, iterable)'], description: '最小堆实现。heapify 将列表转为堆（O(n)），heappush/heappop O(log n)。', example: 'import heapq\nheap = [3, 1, 2]\nheapq.heapify(heap)\nsmallest = heapq.heappop(heap)  # 1', examples: [{ title: '最大堆模拟', code: 'import heapq\nheap = []\nfor x in [1,2,3]:\n  heapq.heappush(heap, -x)\nmx = -heapq.heappop(heap)  # 3' }, { title: 'Top K', code: 'data = [3,1,4,1,5,9,2,6]\nlargest = heapq.nlargest(3, data)  # [9,6,5]\nsmallest = heapq.nsmallest(3, data)  # [1,1,2]' }], complexity: 'heappush/heappop O(log n), heapify O(n)', notes: '默认最小堆。最大堆通过存储负值实现。', leetcode_tips: 'Top K 问题（解法 2）、合并有序链表、Dijkstra 最短路径。', see_also: ['priorityqueue_java', 'priority_queue', 'counter'] },
  { id: 'bisect', name: 'bisect', category: '算法', language: 'python', full_name: 'bisect (二分查找)', signature: 'bisect.bisect_left(a, x) / bisect.bisect_right(a, x)', signatures: ['bisect.bisect_left(a, x, lo=0, hi=len(a))', 'bisect.bisect_right(a, x, lo=0, hi=len(a))', 'bisect.insort(a, x, lo=0, hi=len(a))'], description: '对有序序列的二分查找。bisect_left 返回插入点（左侧），bisect_right 返回插入点（右侧）。', example: 'import bisect\na = [1,2,2,3]\npos = bisect.bisect_left(a, 2)  # 1\npos = bisect.bisect_right(a, 2) # 3', examples: [{ title: '二分查找', code: 'arr = [1,2,4,5]\nidx = bisect.bisect_left(arr, 3)  # 2 (插入位置)\n# 检查元素是否存在\ndef exists(arr, x):\n  i = bisect.bisect_left(arr, x)\n  return i < len(arr) and arr[i] == x' }], complexity: 'O(log n)', notes: 'bisect_left 找第一个 >= x，bisect_right 找第一个 > x。insort 在插入点插入。', leetcode_tips: '最长递增子序列（耐心排序）、二维二分、按值搜索。', see_also: ['lower_upper_bound', 'sorted_reversed'] },
  { id: 'itertools', name: 'itertools', category: '算法', language: 'python', full_name: 'itertools (迭代器工具)', signature: 'itertools.product / permutations / combinations / accumulate', signatures: ['itertools.product(*iterables, repeat=1)', 'itertools.permutations(iterable, r=None)', 'itertools.combinations(iterable, r)', 'itertools.combinations_with_replacement(iterable, r)', 'itertools.accumulate(iterable, func=operator.add)'], description: '高效的迭代器函数库，延迟生成数据，节省内存。', example: 'from itertools import product, permutations, combinations\nlist(product("AB", repeat=2))', examples: [{ title: '排列组合', code: 'from itertools import *\n# 笛卡尔积\nlist(product([1,2], "AB"))  # [(1,"A"),(1,"B"),(2,"A"),(2,"B")]\n# 排列\nlist(permutations([1,2,3], 2))  # 6 项\n# 组合\nlist(combinations([1,2,3], 2))  # 3 项' }, { title: 'accumulate', code: 'list(accumulate([1,2,3,4]))  # [1,3,6,10] 前缀和\nlist(accumulate([1,2,3], lambda x,y: x*y))  # [1,2,6]' }], complexity: '遍历 O(n!) 取决于具体操作', notes: 'itertools 返回迭代器，需 list() 展开。组合数大时注意内存。', leetcode_tips: 'product 做嵌套循环（N 皇后），combinations 找子集，accumulate 前缀和。', see_also: ['map_filter', 'enumerate_zip'] },
  { id: 'functools', name: 'functools', category: '函数式', language: 'python', full_name: 'functools (函数工具)', signature: 'functools.lru_cache / functools.reduce / functools.cmp_to_key', signatures: ['functools.lru_cache(maxsize=128)', 'functools.reduce(function, iterable, initializer)', 'functools.cmp_to_key(func)'], description: '高阶函数工具。lru_cache 缓存函数结果（DP 记忆化），reduce 逐元素累积。', example: 'from functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n  if n < 2: return n\n  return fib(n-1) + fib(n-2)', examples: [{ title: 'LRU Cache 记忆化', code: 'from functools import lru_cache\n@lru_cache(maxsize=None)\ndef dfs(i, j):\n  if i >= m or j >= n: return 0\n  return max(dfs(i+1,j), dfs(i,j+1)) + grid[i][j]' }, { title: 'reduce', code: 'from functools import reduce\nnums = [1,2,3,4]\nprod = reduce(lambda x,y: x*y, nums)  # 24\nfrom operator import mul\nprod = reduce(mul, nums, 1)' }], complexity: '', notes: 'lru_cache 默认 maxsize=128，设为 None 无限缓存。reduce 相当于 fold。', leetcode_tips: 'DFS DP 记忆化用 @lru_cache 极其方便。', see_also: ['itertools', 'map_filter'] },
  { id: 'map_filter', name: 'map / filter', category: '内置函数', language: 'python', full_name: 'map / filter', signature: 'map(func, *iterables) / filter(func, iterable)', signatures: ['map(func, *iterables)', 'filter(func, iterable)'], description: 'map 对可迭代对象每个元素应用函数。filter 过滤满足条件的元素。均返回迭代器。', example: 'list(map(str, [1,2,3]))\nlist(filter(lambda x: x > 0, [-1, 0, 1]))', examples: [{ title: 'map', code: 'nums = [1,2,3]\ndoubled = list(map(lambda x: x*2, nums))\n# list comprehension 通常更 Pythonic:\ndoubled = [x*2 for x in nums]' }, { title: 'filter', code: 'nums = [1,2,3,4,5]\nevens = list(filter(lambda x: x % 2 == 0, nums))\n# [2,4]\n# list comprehension:\nevens = [x for x in nums if x % 2 == 0]' }], complexity: 'O(1) 返回迭代器', notes: 'Python 中 list comprehension 通常比 map/filter 更清晰。', leetcode_tips: '列表推导式通常比 map/filter 更推荐。map 搭配多个可迭代对象时有用。', see_also: ['enumerate_zip', 'any_all', 'py_list'] },
]

console.log('Python entries:', entries.length)

let data = readFileSync('src/data/stl.ts', 'utf8')
data = data.replace(/\n\]$/, '')
data += ',\n'
for (const e of entries) data += entry(e) + ',\n'
data += ']\n'
writeFileSync('src/data/stl.ts', data, 'utf8')
console.log('Appended Python entries successfully')
