import { writeFileSync } from 'fs'

function q(s) { return "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'" }
function qa(arr) { return '[' + arr.map(q).join(', ') + ']' }

function entry(o) {
  let lines = ['  {']
  for (const [k, v] of Object.entries(o)) {
    if (v === undefined || v === null || v === '') continue
    let val
    if (Array.isArray(v)) {
      if (typeof v[0] === 'string') {
        val = qa(v)
      } else {
        // array of objects (examples)
        val = '[' + v.map(ex => {
          let s = '{'
          if (ex.title) s += 'title: ' + q(ex.title) + ', '
          s += 'code: ' + q(ex.code) + '}'
          return s
        }).join(', ') + ']'
      }
    } else if (typeof v === 'string') {
      val = q(v)
    } else {
      val = String(v)
    }
    lines.push('    ' + k + ': ' + val + ',')
  }
  // Remove trailing comma from last field
  let last = lines.pop()
  lines.push(last.replace(/,$/, ''))
  lines.push('  }')
  return lines.join('\n')
}

const entries = [
  // === C++: Sequence Containers ===
  { id: 'vector', name: 'vector', category: '序列容器', language: 'cpp', full_name: 'std::vector<T, Allocator>', signature: 'std::vector<T, Allocator = std::allocator<T>>', signatures: ['std::vector<T, Allocator = std::allocator<T>>'], description: '动态数组，连续内存存储，支持随机访问 O(1) 和尾部插入/删除（均摊 O(1)）。中间插入/删除为 O(n)。', example: '#include <vector>\nstd::vector<int> v = {1, 2, 3};\nv.push_back(4);\nv.pop_back();', examples: [{ title: '基础操作', code: '#include <vector>\nstd::vector<int> v;\nv.push_back(1);\nv.pop_back();\nint x = v.front();\nint y = v.back();\nv.resize(10);\nv.shrink_to_fit();' }], complexity: '随机访问 O(1), 尾部插入均摊 O(1)', notes: 'emplace_back 在 C++11 引入，直接在容器内构造对象，避免拷贝。', leetcode_tips: 'vector<int> 是最常用顺序容器。reserve(n) 配合 push_back 可避免多次扩容。', see_also: ['deque', 'array_cpp', 'list', 'string_cpp'] },
  { id: 'deque', name: 'deque', category: '序列容器', language: 'cpp', full_name: 'std::deque<T>', signature: 'std::deque<T, Allocator = std::allocator<T>>', signatures: ['std::deque<T, Allocator = std::allocator<T>>'], description: '双端队列，分段连续存储，支持头尾 O(1) 插入/删除，随机访问 O(1)。', example: '#include <deque>\nstd::deque<int> dq;\ndq.push_back(1);\ndq.push_front(2);\ndq.pop_front();', examples: [{ title: '双端操作', code: '#include <deque>\nstd::deque<int> dq = {1,2,3};\ndq.push_front(0);\ndq.push_back(4);\nint f = dq.front();\nint b = dq.back();' }], complexity: 'O(1) 头尾操作, O(1) 随机访问', notes: '比 vector 多了头插头删能力，但内存开销稍大。', leetcode_tips: '需要两端操作时用 deque 替代 vector。滑动窗口最大值问题可用 deque 存下标。', see_also: ['vector', 'list', 'array_cpp'] },
  { id: 'list', name: 'list', category: '序列容器', language: 'cpp', full_name: 'std::list<T>', signature: 'std::list<T, Allocator = std::allocator<T>>', signatures: ['std::list<T, Allocator = std::allocator<T>>'], description: '双向链表，任意位置插入/删除 O(1)，不支持随机访问。', example: '#include <list>\nstd::list<int> lst;\nlst.push_back(1);\nlst.push_front(0);', examples: [{ title: '插入与拼接', code: '#include <list>\nstd::list<int> a = {1,2}, b = {3,4};\na.splice(a.end(), b);' }], complexity: '插入/删除 O(1), 访问 O(n)', notes: 'list 的迭代器在插入/删除后依然有效（除被删元素外）。', leetcode_tips: 'LRU Cache 可结合 list 和 unordered_map 实现。splice 是 O(1) 的链表拼接。', see_also: ['vector', 'deque', 'forward_list'] },
  { id: 'array_cpp', name: 'array', category: '序列容器', language: 'cpp', full_name: 'std::array<T, N>', signature: 'std::array<T, N>', signatures: ['std::array<T, N>'], description: '定长数组，栈上分配，大小编译期确定，不支持隐式转换为指针。', example: '#include <array>\nstd::array<int, 3> arr = {1,2,3};', examples: [{ title: '基本用法', code: '#include <array>\nstd::array<int, 5> a{};\na.fill(0);\nfor (int x : a) {}' }], complexity: 'O(1) 随机访问', notes: '相比 C 数组，array 知道自己的大小，有 .size() 方法。', leetcode_tips: '定长数组场景（如 26 个字母计数）用 array 比 vector 更高效。', see_also: ['vector', 'string_cpp'] },
  { id: 'string_cpp', name: 'string (C++)', category: '序列容器', language: 'cpp', full_name: 'std::string', signature: 'std::basic_string<char>', signatures: ['std::basic_string<char>', 'std::wstring', 'std::string_view (C++17)'], description: '动态字符串，连续存储，支持查找、子串、拼接等操作。', example: 'std::string s = "hello";\ns += " world";', examples: [{ title: '基本操作', code: 'std::string s = "leetcode";\ns.substr(0, 4);\ns.find("code");\ns.replace(0, 4, "leet");' }, { title: 'C++17 string_view', code: '#include <string_view>\nstd::string_view sv(s);\nsv.remove_prefix(4);' }], complexity: '查找 O(n), 随机访问 O(1)', notes: 'string 的 find 返回 size_t 类型，npos 表示未找到。', leetcode_tips: '用 string_view 避免拷贝。s[i] - \'0\' 将字符数字转为 int。', see_also: ['vector', 'array_cpp'] },
  // === C++: Associative Containers ===
  { id: 'map', name: 'map', category: '关联容器', language: 'cpp', full_name: 'std::map<K, V>', signature: 'std::map<Key, T, Compare = std::less<Key>>', signatures: ['std::map<Key, T, Compare = std::less<Key>>'], description: '有序键值对映射，基于红黑树，查找/插入/删除 O(log n)。', example: '#include <map>\nstd::map<string, int> m;\nm["alice"] = 1;', examples: [{ title: '遍历与查找', code: 'std::map<int, string> m = {{1,"a"},{2,"b"}};\nfor (auto& [k, v] : m) {}\nauto it = m.find(1);\nif (it != m.end()) {}' }], complexity: 'O(log n) 查找/插入/删除', notes: 'map 按键升序排列。operator[] 会插入默认值。emplace 可避免拷贝。', leetcode_tips: '需要按键排序时用 map。operator[] 前用 count/find 检查存在性。', see_also: ['unordered_map', 'set', 'multimap'] },
  { id: 'unordered_map', name: 'unordered_map', category: '关联容器', language: 'cpp', full_name: 'std::unordered_map<K, V>', signature: 'std::unordered_map<Key, T, Hash = std::hash<Key>>', signatures: ['std::unordered_map<Key, T, Hash = std::hash<Key>>'], description: '无序键值对映射，基于哈希表，平均 O(1) 查找。内存开销比 map 大。', example: '#include <unordered_map>\nstd::unordered_map<string, int> m;\nm["a"]++;', examples: [{ title: '计数用法', code: 'std::unordered_map<char,int> freq;\nfor (char c : s) freq[c]++;\nfor (auto& [k,v] : freq) {}' }], complexity: '平均 O(1), 最坏 O(n)', notes: '自定义键类型需要提供 hash 函数。C++20 支持 contains。', leetcode_tips: '两数之和、字母异位词分组等哈希表题的默认选择。reserve(n) 可减少 rehash。', see_also: ['map', 'unordered_set'] },
  { id: 'set', name: 'set', category: '关联容器', language: 'cpp', full_name: 'std::set<T>', signature: 'std::set<Key, Compare = std::less<Key>>', signatures: ['std::set<Key, Compare = std::less<Key>>'], description: '有序集合，元素唯一，基于红黑树，O(log n) 操作。', example: '#include <set>\nstd::set<int> s = {3,1,2};\ns.insert(4);', examples: [{ title: '集合操作', code: 'std::set<int> a = {1,2,3}, b = {2,3,4};\nset<int> res;\nset_intersection(a,b,inserter(res,res.end()));' }], complexity: 'O(log n) 插入/删除/查找', notes: 'insert 返回 pair<iterator,bool>。set 的元素不可修改。', leetcode_tips: '用于维护有序唯一集合。lower_bound/upper_bound 查找范围。', see_also: ['unordered_set', 'map', 'multiset'] },
  { id: 'unordered_set', name: 'unordered_set', category: '关联容器', language: 'cpp', full_name: 'std::unordered_set<T>', signature: 'std::unordered_set<Key, Hash = std::hash<Key>>', signatures: ['std::unordered_set<Key, Hash = std::hash<Key>>'], description: '无序集合，基于哈希表，平均 O(1) 查找。', example: '#include <unordered_set>\nstd::unordered_set<int> s;\ns.insert(1);', examples: [{ title: '去重用法', code: 'std::vector<int> v = {1,2,2,3};\nstd::unordered_set<int> s(v.begin(), v.end());' }], complexity: '平均 O(1), 最坏 O(n)', notes: '元素无特定顺序。C++20 支持 contains。', leetcode_tips: '判断元素是否出现过、去重等场景的首选。', see_also: ['set', 'unordered_map'] },
  // === C++: Container Adaptors ===
  { id: 'stack', name: 'stack', category: '容器适配器', language: 'cpp', full_name: 'std::stack<T>', signature: 'std::stack<T, Container = std::deque<T>>', signatures: ['std::stack<T, Container = std::deque<T>>'], description: '栈适配器，LIFO。默认底层为 deque。只提供 push/pop/top 操作。', example: '#include <stack>\nstd::stack<int> stk;\nstk.push(1);\nstk.pop();\nint t = stk.top();', examples: [{ title: '栈的应用', code: 'std::stack<int> stk;\nstk.push(10);\nstk.push(20);\nwhile (!stk.empty()) {\n  int t = stk.top(); stk.pop();\n}' }], complexity: 'O(1) 所有操作', notes: 'stack 不提供迭代器，不能遍历。底层容器可以是 deque/vector/list。', leetcode_tips: '括号匹配、单调栈、DFS 模拟都用 stack。', see_also: ['queue', 'priority_queue', 'deque'] },
  { id: 'queue', name: 'queue', category: '容器适配器', language: 'cpp', full_name: 'std::queue<T>', signature: 'std::queue<T, Container = std::deque<T>>', signatures: ['std::queue<T, Container = std::deque<T>>'], description: '队列适配器，FIFO。默认底层为 deque。', example: '#include <queue>\nstd::queue<int> q;\nq.push(1);\nq.pop();\nint f = q.front();', examples: [{ title: 'BFS 队列', code: 'std::queue<int> q;\nq.push(start);\nwhile (!q.empty()) {\n  int cur = q.front(); q.pop();\n}' }], complexity: 'O(1) 所有操作', notes: 'queue 不提供迭代器。底层容器可以是 deque/list。', leetcode_tips: 'BFS、树的层序遍历用 queue。', see_also: ['stack', 'priority_queue', 'deque'] },
  { id: 'priority_queue', name: 'priority_queue', category: '容器适配器', language: 'cpp', full_name: 'std::priority_queue<T>', signature: 'std::priority_queue<T, Container = std::vector<T>, Compare = std::less<T>>', signatures: ['std::priority_queue<T, Container = std::vector<T>, Compare = std::less<T>>'], description: '优先队列（最大堆），默认大的优先。支持 push/pop/top。', example: '#include <queue>\nstd::priority_queue<int> pq;\npq.push(3);\npq.push(1);\npq.push(2);\nint t = pq.top();', examples: [{ title: '最大堆', code: 'std::priority_queue<int> pq;\npq.push(3); pq.push(1); pq.push(2);\n// top() = 3' }, { title: '最小堆', code: 'std::priority_queue<int, vector<int>, greater<int>> min_pq;\nmin_pq.push(3); min_pq.push(1);\n// top() = 1' }], complexity: 'push/pop O(log n), top O(1)', notes: '默认 less<T> 为最大堆。greater<T> 为最小堆。自定义 compare 需 strict weak ordering。', leetcode_tips: 'Top K 问题、合并 K 个有序链表、Dijkstra 算法。', see_also: ['queue', 'stack', 'vector'] },
  // === C++: Utilities ===
  { id: 'pair', name: 'pair', category: '工具', language: 'cpp', full_name: 'std::pair<T1, T2>', signature: 'std::pair<T1, T2>', signatures: ['std::pair<T1, T2>'], description: '存放两个值的简单结构体。支持 ==, <, 结构化绑定。', example: 'std::pair<int, string> p = {1, "a"};\ncout << p.first << p.second;', examples: [{ title: '结构化绑定 (C++17)', code: 'std::pair<int, string> p = {1, "a"};\nauto [id, name] = p;' }], complexity: '', notes: 'make_pair 可自动推导类型。pair 默认按 first, second 字典序比较。', leetcode_tips: 'map 的元素类型就是 pair<const Key, T>。', see_also: ['tuple', 'map'] },
  { id: 'tuple', name: 'tuple', category: '工具', language: 'cpp', full_name: 'std::tuple<Types...>', signature: 'std::tuple<Types...>', signatures: ['std::tuple<Types...>'], description: '存放任意数量不同类型值的定长元组。', example: '#include <tuple>\nstd::tuple<int, double, string> t = {1, 2.5, "a"};', examples: [{ title: '访问与解包', code: 'auto t = std::make_tuple(1, 2.5, "a");\nauto [a, b, c] = t; // C++17 structured binding' }], complexity: '', notes: '用 std::get<0>(t) 或 std::get<int>(t) 访问。tuple_cat 可拼接。', leetcode_tips: '需要返回多个值时用 tuple 替代 pair。', see_also: ['pair'] },
  { id: 'optional', name: 'optional', category: '工具', language: 'cpp', full_name: 'std::optional<T> (C++17)', signature: 'std::optional<T>', signatures: ['std::optional<T>'], description: '可能包含值也可能不包含的类型，替代指针或哨兵值。', example: '#include <optional>\nstd::optional<int> o = 42;\nif (o) { int v = o.value(); }', examples: [{ title: '函数返回 optional', code: 'std::optional<int> safe_div(int a, int b) {\n  if (b == 0) return std::nullopt;\n  return a / b;\n}' }], complexity: '', notes: 'value_or(default) 提供默认值。没有值时可抛 std::bad_optional_access。', leetcode_tips: '查找未找到时用 optional 替代 -1 或 nullptr。', see_also: ['variant', 'any', 'shared_ptr'] },
  { id: 'variant', name: 'variant', category: '工具', language: 'cpp', full_name: 'std::variant<Types...> (C++17)', signature: 'std::variant<Types...>', signatures: ['std::variant<Types...>'], description: '类型安全的联合体，存储多种类型中的一种。', example: '#include <variant>\nstd::variant<int, string> v = 42;\nv = "hello";\nstd::visit([](auto&&){}, v);', examples: [{ title: 'visit 模式', code: 'std::variant<int, string> v;\nv = 42;\nstd::visit([](auto&& val) { cout << val; }, v);' }], complexity: '', notes: 'get_if<T>() 判断当前类型。bad_variant_access 异常。', leetcode_tips: '不同类型节点的抽象语法树可以用 variant。', see_also: ['optional', 'any'] },
  // === C++: Algorithms ===
  { id: 'sort', name: 'sort', category: '算法', language: 'cpp', full_name: 'std::sort', signature: 'void sort(RandomIt first, RandomIt last, Compare comp = {})', signatures: ['void sort(RandomIt first, RandomIt last)', 'void sort(RandomIt first, RandomIt last, Compare comp)'], description: '对范围内的元素排序，平均 O(n log n)。IntroSort 混合算法。', example: '#include <algorithm>\nstd::vector<int> v = {3,1,2};\nstd::sort(v.begin(), v.end());', examples: [{ title: '自定义排序', code: 'vector<pair<int,int>> v = {{1,2},{2,1}};\nsort(v.begin(), v.end(), [](auto& a, auto& b) {\n  return a.second < b.second;\n});' }, { title: '降序', code: 'vector<int> v = {1,2,3};\nsort(v.begin(), v.end(), greater<int>());' }], complexity: 'O(n log n)', notes: '要求随机访问迭代器（vector, deque, array 可用，list 不可用）。', leetcode_tips: '排序后常配合双指针或二分查找。部分排序用 nth_element。', see_also: ['stable_sort', 'partial_sort', 'nth_element'] },
  { id: 'lower_upper_bound', name: 'lower_bound / upper_bound', category: '算法', language: 'cpp', full_name: 'std::lower_bound / std::upper_bound', signature: 'ForwardIt lower_bound(ForwardIt first, ForwardIt last, const T& value)', signatures: ['ForwardIt lower_bound(ForwardIt first, ForwardIt last, const T& value)', 'ForwardIt upper_bound(ForwardIt first, ForwardIt last, const T& value)', 'bool binary_search(ForwardIt first, ForwardIt last, const T& value)'], description: '对有序范围进行二分查找。lower_bound 返回首个 >= value 的位置，upper_bound 返回首个 > value 的位置。', example: '#include <algorithm>\nstd::vector<int> v = {1,2,2,3,4};\nauto it = std::lower_bound(v.begin(), v.end(), 2);', examples: [{ title: '区间查找', code: 'vector<int> v = {1,2,2,3,4};\nint l = lower_bound(v.begin(),v.end(),2) - v.begin();\nint r = upper_bound(v.begin(),v.end(),2) - v.begin();\nint cnt = r - l;\nbool ok = binary_search(v.begin(),v.end(),2);' }], returns: 'lower_bound/upper_bound 返回迭代器，binary_search 返回 bool', complexity: 'O(log n)', notes: '必须在有序范围上使用。lower_bound - begin() 获取下标。', leetcode_tips: '二分答案常用：对有序数组用 lower_bound 找第一个 >= target 的元素。', see_also: ['sort', 'equal_range', 'binary_search'] },
  { id: 'reverse_accumulate', name: 'reverse / accumulate', category: '算法', language: 'cpp', full_name: 'std::reverse / std::accumulate', signature: 'void reverse(BidirIt first, BidirIt last)', signatures: ['void reverse(BidirIt first, BidirIt last)', 'T accumulate(InputIt first, InputIt last, T init)', 'T accumulate(InputIt first, InputIt last, T init, BinaryOp op)'], description: 'reverse 反转范围内的元素顺序。accumulate 累加范围内的值。', example: '#include <numeric>\nstd::vector<int> v = {1,2,3};\nint sum = std::accumulate(v.begin(), v.end(), 0);', examples: [{ title: 'accumulate', code: 'vector<int> v = {1,2,3};\nint sum = accumulate(v.begin(), v.end(), 0);\nint prod = accumulate(v.begin(), v.end(), 1, multiplies<int>());' }, { title: 'reverse', code: 'vector<int> v = {1,2,3};\nreverse(v.begin(), v.end()); // {3,2,1}' }], returns: 'reverse 无返回值，accumulate 返回累加值', complexity: 'reverse O(n), accumulate O(n)', notes: 'reverse 要求双向迭代器。accumulate 在 <numeric> 中。', leetcode_tips: '字符串反转、链表反转常用 reverse 或自定义。accumulate 的 init 类型决定返回类型。', see_also: ['sort', 'for_each', 'transform'] },
  { id: 'bitset', name: 'bitset', category: '工具', language: 'cpp', full_name: 'std::bitset<N>', signature: 'std::bitset<N>', signatures: ['std::bitset<N>'], description: '固定大小的位集合，编译期决定大小。支持位运算 & | ^ ~ << >>。', example: '#include <bitset>\nstd::bitset<8> b(0b1010);\nb.set(2);\nb.reset(1);\nb.flip();', examples: [{ title: '位集操作', code: 'std::bitset<8> b("10101010");\nb.count();\nb.any();\nb.test(3);' }], complexity: 'O(n) 大多数操作', notes: 'bitset 比 vector<bool> 更高效，位运算时间复杂度与 N/word_size 相关。', leetcode_tips: '状态压缩 DP 可以用 bitset 优化。count() 统计 1 的个数。', see_also: ['vector'] },
  { id: 'shared_ptr', name: 'shared_ptr / unique_ptr', category: '智能指针', language: 'cpp', full_name: 'std::shared_ptr<T> / std::unique_ptr<T>', signature: 'std::shared_ptr<T> / std::unique_ptr<T>', signatures: ['std::shared_ptr<T> (C++11)', 'std::unique_ptr<T> (C++11)', 'auto make_shared<T>(Args&&...)', 'auto make_unique<T>(Args&&...)'], description: 'shared_ptr 引用计数共享所有权，unique_ptr 独占所有权。make_shared/make_unique 推荐创建方式。', example: '#include <memory>\nauto sp = std::make_shared<int>(42);\nauto up = std::make_unique<int>(42);', examples: [{ title: 'shared_ptr', code: 'auto sp = make_shared<int>(42);\n{ auto sp2 = sp; cout << sp.use_count(); }' }, { title: 'unique_ptr 转移', code: 'auto up = make_unique<int>(42);\nauto up2 = std::move(up);' }], complexity: '', notes: 'make_shared 比 new + shared_ptr 更高效。unique_ptr 不可复制，只能移动。', leetcode_tips: '链表、树等递归结构用 unique_ptr 或裸指针即可，shared_ptr 有循环引用风险。', see_also: ['optional', 'variant'] },
]

console.log('Total entries:', entries.length)
let result = "import type { ApiEntry } from '../types'\n\nexport const apiData: ApiEntry[] = [\n"
for (const e of entries) result += entry(e) + ',\n'
result += ']\n'
writeFileSync('src/data/stl.ts', result, 'utf8')
console.log('Written to src/data/stl.ts')
