import { writeFileSync } from 'fs'

function esc(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
}

function q(s) { return "'" + esc(s) + "'" }
function qa(arr) { return '[' + arr.map(q).join(', ') + ']' }

function entry(o) {
  let lines = ['  {']
  for (const [k, v] of Object.entries(o)) {
    if (v === undefined || v === null || v === '') continue
    let val
    if (Array.isArray(v)) {
      if (typeof v[0] === 'string') {
        val = qa(v)
      } else {
        // array of objects (examples)
        val = '[' + v.map(ex => {
          let s = '{'
          if (ex.title) s += 'title: ' + q(ex.title) + ', '
          s += 'code: ' + q(ex.code) + '}'
          return s
        }).join(', ') + ']'
      }
    } else if (typeof v === 'string') {
      val = q(v)
    } else {
      val = String(v)
    }
    lines.push('    ' + k + ': ' + val + ',')
  }
  let last = lines.pop()
  lines.push(last.replace(/,$/, ''))
  lines.push('  }')
  return lines.join('\n')
}

function add(o) { entries.push(o) }

const entries = []

// === C++: Sequence Containers ===
add({ id: 'vector', name: 'vector', category: '序列容器', language: 'cpp', full_name: 'std::vector<T, Allocator>', signature: 'std::vector<T, Allocator = std::allocator<T>>', signatures: ['std::vector<T, Allocator = std::allocator<T>>'], description: '动态数组，连续内存存储，支持随机访问 O(1) 和尾部插入/删除（均摊 O(1)）。中间插入/删除为 O(n)。', example: '#include <vector>\nstd::vector<int> v = {1, 2, 3};\nv.push_back(4);\nv.pop_back();', examples: [{ title: '基础操作', code: '#include <vector>\nstd::vector<int> v;\nv.push_back(1);\nv.pop_back();\nint x = v.front();\nint y = v.back();\nv.resize(10);\nv.shrink_to_fit();' }], complexity: '随机访问 O(1), 尾部插入均摊 O(1)', notes: 'emplace_back 在 C++11 引入，直接在容器内构造对象，避免拷贝。', leetcode_tips: 'vector<int> 是最常用顺序容器。reserve(n) 配合 push_back 可避免多次扩容。', see_also: ['deque', 'array_cpp', 'list', 'string_cpp'] })
add({ id: 'deque', name: 'deque', category: '序列容器', language: 'cpp', full_name: 'std::deque<T>', signature: 'std::deque<T, Allocator = std::allocator<T>>', signatures: ['std::deque<T, Allocator = std::allocator<T>>'], description: '双端队列，分段连续存储，支持头尾 O(1) 插入/删除，随机访问 O(1)。', example: '#include <deque>\nstd::deque<int> dq;\ndq.push_back(1);\ndq.push_front(2);\ndq.pop_front();', examples: [{ title: '双端操作', code: '#include <deque>\nstd::deque<int> dq = {1,2,3};\ndq.push_front(0);\ndq.push_back(4);\nint f = dq.front();\nint b = dq.back();' }], complexity: 'O(1) 头尾操作, O(1) 随机访问', notes: '比 vector 多了头插头删能力，但内存开销稍大。', leetcode_tips: '需要两端操作时用 deque 替代 vector。滑动窗口最大值问题可用 deque 存下标。', see_also: ['vector', 'list', 'array_cpp'] })
add({ id: 'list', name: 'list', category: '序列容器', language: 'cpp', full_name: 'std::list<T>', signature: 'std::list<T, Allocator = std::allocator<T>>', signatures: ['std::list<T, Allocator = std::allocator<T>>'], description: '双向链表，任意位置插入/删除 O(1)，不支持随机访问。', example: '#include <list>\nstd::list<int> lst;\nlst.push_back(1);\nlst.push_front(0);', examples: [{ title: '插入与拼接', code: '#include <list>\nstd::list<int> a = {1,2}, b = {3,4};\na.splice(a.end(), b);' }], complexity: '插入/删除 O(1), 访问 O(n)', notes: 'list 的迭代器在插入/删除后依然有效（除被删元素外）。', leetcode_tips: 'LRU Cache 可结合 list 和 unordered_map 实现。splice 是 O(1) 的链表拼接。', see_also: ['vector', 'deque', 'forward_list'] })
add({ id: 'array_cpp', name: 'array', category: '序列容器', language: 'cpp', full_name: 'std::array<T, N>', signature: 'std::array<T, N>', signatures: ['std::array<T, N>'], description: '定长数组，栈上分配，大小编译期确定，不支持隐式转换为指针。', example: '#include <array>\nstd::array<int, 3> arr = {1,2,3};', examples: [{ title: '基本用法', code: '#include <array>\nstd::array<int, 5> a{};\na.fill(0);\nfor (int x : a) {}' }], complexity: 'O(1) 随机访问', notes: '相比 C 数组，array 知道自己的大小，有 .size() 方法。', leetcode_tips: '定长数组场景（如 26 个字母计数）用 array 比 vector 更高效。', see_also: ['vector', 'string_cpp'] })
add({ id: 'string_cpp', name: 'string (C++)', category: '序列容器', language: 'cpp', full_name: 'std::string', signature: 'std::basic_string<char>', signatures: ['std::basic_string<char>', 'std::wstring', 'std::string_view (C++17)'], description: '动态字符串，连续存储，支持查找、子串、拼接等操作。', example: 'std::string s = "hello";\ns += " world";', examples: [{ title: '基本操作', code: 'std::string s = "leetcode";\ns.substr(0, 4);\ns.find("code");\ns.replace(0, 4, "leet");' }, { title: 'C++17 string_view', code: '#include <string_view>\nstd::string_view sv(s);\nsv.remove_prefix(4);' }], complexity: '查找 O(n), 随机访问 O(1)', notes: 'string 的 find 返回 size_t 类型，npos 表示未找到。', leetcode_tips: '用 string_view 避免拷贝。s[i] - \'0\' 将字符数字转为 int。', see_also: ['vector', 'array_cpp'] })
// === C++: Associative Containers ===
add({ id: 'map', name: 'map', category: '关联容器', language: 'cpp', full_name: 'std::map<K, V>', signature: 'std::map<Key, T, Compare = std::less<Key>>', signatures: ['std::map<Key, T, Compare = std::less<Key>>'], description: '有序键值对映射，基于红黑树，查找/插入/删除 O(log n)。', example: '#include <map>\nstd::map<string, int> m;\nm["alice"] = 1;', examples: [{ title: '遍历与查找', code: 'std::map<int, string> m = {{1,"a"},{2,"b"}};\nfor (auto& [k, v] : m) {}\nauto it = m.find(1);\nif (it != m.end()) {}' }], complexity: 'O(log n) 查找/插入/删除', notes: 'map 按键升序排列。operator[] 会插入默认值。emplace 可避免拷贝。', leetcode_tips: '需要按键排序时用 map。operator[] 前用 count/find 检查存在性。', see_also: ['unordered_map', 'set', 'multimap'] })
add({ id: 'unordered_map', name: 'unordered_map', category: '关联容器', language: 'cpp', full_name: 'std::unordered_map<K, V>', signature: 'std::unordered_map<Key, T, Hash = std::hash<Key>>', signatures: ['std::unordered_map<Key, T, Hash = std::hash<Key>>'], description: '无序键值对映射，基于哈希表，平均 O(1) 查找。内存开销比 map 大。', example: '#include <unordered_map>\nstd::unordered_map<string, int> m;\nm["a"]++;', examples: [{ title: '计数用法', code: 'std::unordered_map<char,int> freq;\nfor (char c : s) freq[c]++;\nfor (auto& [k,v] : freq) {}' }], complexity: '平均 O(1), 最坏 O(n)', notes: '自定义键类型需要提供 hash 函数。C++20 支持 contains。', leetcode_tips: '两数之和、字母异位词分组等哈希表题的默认选择。reserve(n) 可减少 rehash。', see_also: ['map', 'unordered_set'] })
add({ id: 'set', name: 'set', category: '关联容器', language: 'cpp', full_name: 'std::set<T>', signature: 'std::set<Key, Compare = std::less<Key>>', signatures: ['std::set<Key, Compare = std::less<Key>>'], description: '有序集合，元素唯一，基于红黑树，O(log n) 操作。', example: '#include <set>\nstd::set<int> s = {3,1,2};\ns.insert(4);', examples: [{ title: '集合操作', code: 'std::set<int> a = {1,2,3}, b = {2,3,4};\nset<int> res;\nset_intersection(a,b,inserter(res,res.end()));' }], complexity: 'O(log n) 插入/删除/查找', notes: 'insert 返回 pair<iterator,bool>。set 的元素不可修改。', leetcode_tips: '用于维护有序唯一集合。lower_bound/upper_bound 查找范围。', see_also: ['unordered_set', 'map', 'multiset'] })
add({ id: 'unordered_set', name: 'unordered_set', category: '关联容器', language: 'cpp', full_name: 'std::unordered_set<T>', signature: 'std::unordered_set<Key, Hash = std::hash<Key>>', signatures: ['std::unordered_set<Key, Hash = std::hash<Key>>'], description: '无序集合，基于哈希表，平均 O(1) 查找。', example: '#include <unordered_set>\nstd::unordered_set<int> s;\ns.insert(1);', examples: [{ title: '去重用法', code: 'std::vector<int> v = {1,2,2,3};\nstd::unordered_set<int> s(v.begin(), v.end());' }], complexity: '平均 O(1), 最坏 O(n)', notes: '元素无特定顺序。C++20 支持 contains。', leetcode_tips: '判断元素是否出现过、去重等场景的首选。', see_also: ['set', 'unordered_map'] })
// === C++: Container Adaptors ===
add({ id: 'stack', name: 'stack', category: '容器适配器', language: 'cpp', full_name: 'std::stack<T>', signature: 'std::stack<T, Container = std::deque<T>>', signatures: ['std::stack<T, Container = std::deque<T>>'], description: '栈适配器，LIFO。默认底层为 deque。只提供 push/pop/top 操作。', example: '#include <stack>\nstd::stack<int> stk;\nstk.push(1);\nstk.pop();\nint t = stk.top();', examples: [{ title: '栈的应用', code: 'std::stack<int> stk;\nstk.push(10);\nstk.push(20);\nwhile (!stk.empty()) {\n  int t = stk.top(); stk.pop();\n}' }], complexity: 'O(1) 所有操作', notes: 'stack 不提供迭代器，不能遍历。底层容器可以是 deque/vector/list。', leetcode_tips: '括号匹配、单调栈、DFS 模拟都用 stack。', see_also: ['queue', 'priority_queue', 'deque'] })
add({ id: 'queue', name: 'queue', category: '容器适配器', language: 'cpp', full_name: 'std::queue<T>', signature: 'std::queue<T, Container = std::deque<T>>', signatures: ['std::queue<T, Container = std::deque<T>>'], description: '队列适配器，FIFO。默认底层为 deque。', example: '#include <queue>\nstd::queue<int> q;\nq.push(1);\nq.pop();\nint f = q.front();', examples: [{ title: 'BFS 队列', code: 'std::queue<int> q;\nq.push(start);\nwhile (!q.empty()) {\n  int cur = q.front(); q.pop();\n}' }], complexity: 'O(1) 所有操作', notes: 'queue 不提供迭代器。底层容器可以是 deque/list。', leetcode_tips: 'BFS、树的层序遍历用 queue。', see_also: ['stack', 'priority_queue', 'deque'] })
add({ id: 'priority_queue', name: 'priority_queue', category: '容器适配器', language: 'cpp', full_name: 'std::priority_queue<T>', signature: 'std::priority_queue<T, Container = std::vector<T>, Compare = std::less<T>>', signatures: ['std::priority_queue<T, Container = std::vector<T>, Compare = std::less<T>>'], description: '优先队列（最大堆），默认大的优先。支持 push/pop/top。', example: '#include <queue>\nstd::priority_queue<int> pq;\npq.push(3);\npq.push(1);\npq.push(2);\nint t = pq.top();', examples: [{ title: '最大堆', code: 'std::priority_queue<int> pq;\npq.push(3); pq.push(1); pq.push(2);\n// top() = 3' }, { title: '最小堆', code: 'std::priority_queue<int, vector<int>, greater<int>> min_pq;\nmin_pq.push(3); min_pq.push(1);\n// top() = 1' }], complexity: 'push/pop O(log n), top O(1)', notes: '默认 less<T> 为最大堆。greater<T> 为最小堆。自定义 compare 需 strict weak ordering。', leetcode_tips: 'Top K 问题、合并 K 个有序链表、Dijkstra 算法。', see_also: ['queue', 'stack', 'vector'] })
// === C++: Utilities ===
add({ id: 'pair', name: 'pair', category: '工具', language: 'cpp', full_name: 'std::pair<T1, T2>', signature: 'std::pair<T1, T2>', signatures: ['std::pair<T1, T2>'], description: '存放两个值的简单结构体。支持 ==, <, 结构化绑定。', example: 'std::pair<int, string> p = {1, "a"};\ncout << p.first << p.second;', examples: [{ title: '结构化绑定 (C++17)', code: 'std::pair<int, string> p = {1, "a"};\nauto [id, name] = p;' }], complexity: '', notes: 'make_pair 可自动推导类型。pair 默认按 first, second 字典序比较。', leetcode_tips: 'map 的元素类型就是 pair<const Key, T>。', see_also: ['tuple', 'map'] })
add({ id: 'tuple', name: 'tuple', category: '工具', language: 'cpp', full_name: 'std::tuple<Types...>', signature: 'std::tuple<Types...>', signatures: ['std::tuple<Types...>'], description: '存放任意数量不同类型值的定长元组。', example: '#include <tuple>\nstd::tuple<int, double, string> t = {1, 2.5, "a"};', examples: [{ title: '访问与解包', code: 'auto t = std::make_tuple(1, 2.5, "a");\nauto [a, b, c] = t;' }], complexity: '', notes: '用 std::get<0>(t) 或 std::get<int>(t) 访问。tuple_cat 可拼接。', leetcode_tips: '需要返回多个值时用 tuple 替代 pair。', see_also: ['pair'] })
add({ id: 'optional', name: 'optional', category: '工具', language: 'cpp', full_name: 'std::optional<T> (C++17)', signature: 'std::optional<T>', signatures: ['std::optional<T>'], description: '可能包含值也可能不包含的类型，替代指针或哨兵值。', example: '#include <optional>\nstd::optional<int> o = 42;\nif (o) { int v = o.value(); }', examples: [{ title: '函数返回 optional', code: 'std::optional<int> safe_div(int a, int b) {\n  if (b == 0) return std::nullopt;\n  return a / b;\n}' }], complexity: '', notes: 'value_or(default) 提供默认值。没有值时可抛 std::bad_optional_access。', leetcode_tips: '查找未找到时用 optional 替代 -1 或 nullptr。', see_also: ['variant', 'any', 'shared_ptr'] })
add({ id: 'variant', name: 'variant', category: '工具', language: 'cpp', full_name: 'std::variant<Types...> (C++17)', signature: 'std::variant<Types...>', signatures: ['std::variant<Types...>'], description: '类型安全的联合体，存储多种类型中的一种。', example: '#include <variant>\nstd::variant<int, string> v = 42;\nv = "hello";\nstd::visit([](auto&&){}, v);', examples: [{ title: 'visit 模式', code: 'std::variant<int, string> v;\nv = 42;\nstd::visit([](auto&& val) { cout << val; }, v);' }], complexity: '', notes: 'get_if<T>() 判断当前类型。bad_variant_access 异常。', leetcode_tips: '不同类型节点的抽象语法树可以用 variant。', see_also: ['optional', 'any'] })
// === C++: Algorithms ===
add({ id: 'sort', name: 'sort', category: '算法', language: 'cpp', full_name: 'std::sort', signature: 'void sort(RandomIt first, RandomIt last, Compare comp = {})', signatures: ['void sort(RandomIt first, RandomIt last)', 'void sort(RandomIt first, RandomIt last, Compare comp)'], description: '对范围内的元素排序，平均 O(n log n)。IntroSort 混合算法。', example: '#include <algorithm>\nstd::vector<int> v = {3,1,2};\nstd::sort(v.begin(), v.end());', examples: [{ title: '自定义排序', code: 'vector<pair<int,int>> v = {{1,2},{2,1}};\nsort(v.begin(), v.end(), [](auto& a, auto& b) {\n  return a.second < b.second;\n});' }, { title: '降序', code: 'vector<int> v = {1,2,3};\nsort(v.begin(), v.end(), greater<int>());' }], complexity: 'O(n log n)', notes: '要求随机访问迭代器（vector, deque, array 可用，list 不可用）。', leetcode_tips: '排序后常配合双指针或二分查找。部分排序用 nth_element。', see_also: ['stable_sort', 'partial_sort', 'nth_element'] })
add({ id: 'lower_upper_bound', name: 'lower_bound / upper_bound', category: '算法', language: 'cpp', full_name: 'std::lower_bound / std::upper_bound', signature: 'ForwardIt lower_bound(ForwardIt first, ForwardIt last, const T& value)', signatures: ['ForwardIt lower_bound(ForwardIt first, ForwardIt last, const T& value)', 'ForwardIt upper_bound(ForwardIt first, ForwardIt last, const T& value)', 'bool binary_search(ForwardIt first, ForwardIt last, const T& value)'], description: '对有序范围进行二分查找。lower_bound 返回首个 >= value 的位置，upper_bound 返回首个 > value 的位置。', example: '#include <algorithm>\nstd::vector<int> v = {1,2,2,3,4};\nauto it = std::lower_bound(v.begin(), v.end(), 2);', examples: [{ title: '区间查找', code: 'vector<int> v = {1,2,2,3,4};\nint l = lower_bound(v.begin(),v.end(),2) - v.begin();\nint r = upper_bound(v.begin(),v.end(),2) - v.begin();\nint cnt = r - l;\nbool ok = binary_search(v.begin(),v.end(),2);' }], returns: 'lower_bound/upper_bound 返回迭代器，binary_search 返回 bool', complexity: 'O(log n)', notes: '必须在有序范围上使用。lower_bound - begin() 获取下标。', leetcode_tips: '二分答案常用：对有序数组用 lower_bound 找第一个 >= target 的元素。', see_also: ['sort', 'equal_range', 'binary_search'] })
add({ id: 'reverse_accumulate', name: 'reverse / accumulate', category: '算法', language: 'cpp', full_name: 'std::reverse / std::accumulate', signature: 'void reverse(BidirIt first, BidirIt last)', signatures: ['void reverse(BidirIt first, BidirIt last)', 'T accumulate(InputIt first, InputIt last, T init)', 'T accumulate(InputIt first, InputIt last, T init, BinaryOp op)'], description: 'reverse 反转范围内的元素顺序。accumulate 累加范围内的值。', example: '#include <numeric>\nstd::vector<int> v = {1,2,3};\nint sum = std::accumulate(v.begin(), v.end(), 0);', examples: [{ title: 'accumulate', code: 'vector<int> v = {1,2,3};\nint sum = accumulate(v.begin(), v.end(), 0);\nint prod = accumulate(v.begin(), v.end(), 1, multiplies<int>());' }, { title: 'reverse', code: 'vector<int> v = {1,2,3};\nreverse(v.begin(), v.end());' }], returns: 'reverse 无返回值，accumulate 返回累加值', complexity: 'reverse O(n), accumulate O(n)', notes: 'reverse 要求双向迭代器。accumulate 在 <numeric> 中。', leetcode_tips: '字符串反转、链表反转常用 reverse 或自定义。accumulate 的 init 类型决定返回类型。', see_also: ['sort', 'for_each', 'transform'] })
add({ id: 'bitset', name: 'bitset', category: '工具', language: 'cpp', full_name: 'std::bitset<N>', signature: 'std::bitset<N>', signatures: ['std::bitset<N>'], description: '固定大小的位集合，编译期决定大小。支持位运算 & | ^ ~ << >>。', example: '#include <bitset>\nstd::bitset<8> b(0b1010);\nb.set(2);\nb.reset(1);\nb.flip();', examples: [{ title: '位集操作', code: 'std::bitset<8> b("10101010");\nb.count();\nb.any();\nb.test(3);' }], complexity: 'O(n) 大多数操作', notes: 'bitset 比 vector<bool> 更高效，位运算时间复杂度与 N/word_size 相关。', leetcode_tips: '状态压缩 DP 可以用 bitset 优化。count() 统计 1 的个数。', see_also: ['vector'] })
add({ id: 'shared_ptr', name: 'shared_ptr / unique_ptr', category: '智能指针', language: 'cpp', full_name: 'std::shared_ptr<T> / std::unique_ptr<T>', signature: 'std::shared_ptr<T> / std::unique_ptr<T>', signatures: ['std::shared_ptr<T> (C++11)', 'std::unique_ptr<T> (C++11)', 'auto make_shared<T>(Args&&...)', 'auto make_unique<T>(Args&&...)'], description: 'shared_ptr 引用计数共享所有权，unique_ptr 独占所有权。make_shared/make_unique 推荐创建方式。', example: '#include <memory>\nauto sp = std::make_shared<int>(42);\nauto up = std::make_unique<int>(42);', examples: [{ title: 'shared_ptr', code: 'auto sp = make_shared<int>(42);\n{ auto sp2 = sp; cout << sp.use_count(); }' }, { title: 'unique_ptr 转移', code: 'auto up = make_unique<int>(42);\nauto up2 = std::move(up);' }], complexity: '', notes: 'make_shared 比 new + shared_ptr 更高效。unique_ptr 不可复制，只能移动。', leetcode_tips: '链表、树等递归结构用 unique_ptr 或裸指针即可，shared_ptr 有循环引用风险。', see_also: ['optional', 'variant'] })
// === Java ===
add({ id: 'arraylist', name: 'ArrayList', category: '集合类', language: 'java', full_name: 'java.util.ArrayList<E>', signature: 'ArrayList<E>', signatures: ['ArrayList<E>'], description: '动态数组，连续存储，随机访问 O(1)，尾部插入均摊 O(1)。中间插入/删除 O(n)。', example: 'ArrayList<Integer> list = new ArrayList<>();\nlist.add(1);\nlist.get(0);', examples: [{ title: '基本操作', code: 'ArrayList<String> list = new ArrayList<>();\nlist.add("a");\nlist.add(0, "b");\nlist.remove(0);\nlist.contains("a");\nlist.size();' }], complexity: '随机访问 O(1), 尾部插入均摊 O(1)', notes: 'ArrayList 是 List 接口的可变大小数组实现。ensureCapacity 可预分配。', leetcode_tips: 'Arrays.asList() 返回固定大小列表，不能 add/remove。List.of() (Java 9+) 返回不可变列表。', see_also: ['linkedlist', 'arrays'] })
add({ id: 'linkedlist', name: 'LinkedList', category: '集合类', language: 'java', full_name: 'java.util.LinkedList<E>', signature: 'LinkedList<E>', signatures: ['LinkedList<E>'], description: '双向链表，实现 List 和 Deque 接口。头尾操作 O(1)，中间插入 O(n)。', example: 'LinkedList<String> list = new LinkedList<>();\nlist.addFirst("a");\nlist.addLast("b");', examples: [{ title: '双端操作', code: 'LinkedList<Integer> dq = new LinkedList<>();\ndq.addFirst(1);\ndq.addLast(2);\ndq.peekFirst();\ndq.pollLast();' }], complexity: '头尾 O(1), 随机访问 O(n)', notes: '可作 List、Queue、Deque 使用。注意随机访问性能较差。', leetcode_tips: '实现 Deque 接口，可替代 Stack。推荐用 LinkedList 作为队列实现。', see_also: ['arraylist', 'arraydeque'] })
add({ id: 'hashmap', name: 'HashMap', category: '集合类', language: 'java', full_name: 'java.util.HashMap<K, V>', signature: 'HashMap<K, V>', signatures: ['HashMap<K, V>'], description: '基于哈希表的 Map 实现，允许 key/value 为 null。平均 O(1) 查找。', example: 'HashMap<String, Integer> map = new HashMap<>();\nmap.put("a", 1);\nint v = map.get("a");', examples: [{ title: '计数用法', code: 'HashMap<Character, Integer> freq = new HashMap<>();\nfor (char c : s.toCharArray()) {\n  freq.put(c, freq.getOrDefault(c, 0) + 1);\n}' }], complexity: '平均 O(1), 最坏 O(n)', notes: '初始容量和负载因子影响性能。Java 8+ 链表长度 >8 转红黑树。', leetcode_tips: '两数之和、滑动窗口计数、频次统计等的默认选择。', see_also: ['treemap', 'linkedhashmap', 'hashset'] })
add({ id: 'treemap', name: 'TreeMap', category: '集合类', language: 'java', full_name: 'java.util.TreeMap<K, V>', signature: 'TreeMap<K, V>', signatures: ['TreeMap<K, V>'], description: '基于红黑树的有序 Map，按键自然序或 Comparator 排序。O(log n) 操作。', example: 'TreeMap<Integer, String> map = new TreeMap<>();\nmap.put(1, "a");\nmap.firstKey();', examples: [{ title: '范围操作', code: 'TreeMap<Integer, String> tm = new TreeMap<>();\ntm.put(1,"a"); tm.put(3,"c"); tm.put(2,"b");\ntm.firstKey();\ntm.lastKey();\ntm.ceilingKey(2);\ntm.floorKey(2);' }], complexity: 'O(log n)', notes: 'NavigableMap 和 SortedMap 接口的实现。支持 range view。', leetcode_tips: '需要有序键、floor/ceiling 操作时用 TreeMap。', see_also: ['hashmap', 'linkedhashmap', 'treeset'] })
add({ id: 'hashset', name: 'HashSet', category: '集合类', language: 'java', full_name: 'java.util.HashSet<E>', signature: 'HashSet<E>', signatures: ['HashSet<E>'], description: '基于 HashMap 的 Set 实现，不允许重复元素。平均 O(1) 操作。', example: 'HashSet<Integer> set = new HashSet<>();\nset.add(1);\nset.contains(1);', examples: [{ title: '去重用法', code: 'HashSet<Integer> seen = new HashSet<>();\nfor (int x : nums) {\n  if (seen.contains(x)) return true;\n  seen.add(x);\n}' }], complexity: '平均 O(1)', notes: '元素无序。LinkedHashSet 保持插入顺序，TreeSet 保持排序。', leetcode_tips: '判断元素是否出现过、去重的首选。', see_also: ['treeset', 'linkedhashset', 'hashmap'] })
add({ id: 'treeset', name: 'TreeSet', category: '集合类', language: 'java', full_name: 'java.util.TreeSet<E>', signature: 'TreeSet<E>', signatures: ['TreeSet<E>'], description: '基于 TreeMap 的有序 Set，红黑树实现。O(log n) 操作。', example: 'TreeSet<Integer> ts = new TreeSet<>();\nts.add(3); ts.add(1); ts.add(2);', examples: [{ title: '范围查询', code: 'TreeSet<Integer> ts = new TreeSet<>(Set.of(1,3,5,7));\nts.ceiling(4);\nts.floor(4);\nts.higher(5);\nts.lower(5);' }], complexity: 'O(log n)', notes: 'NavigableSet 接口的实现。ceiling/floor/higher/lower 方法很实用。', leetcode_tips: '有序集合场景，如滑动窗口中的值范围维护。', see_also: ['hashset', 'treemap', 'linkedhashset'] })
add({ id: 'stringbuilder', name: 'StringBuilder', category: '字符串', language: 'java', full_name: 'java.lang.StringBuilder', signature: 'StringBuilder', signatures: ['StringBuilder'], description: '可变字符串，适合频繁拼接操作(append/concat)，非线程安全。', example: 'StringBuilder sb = new StringBuilder();\nsb.append("a");\nsb.append("b");\nsb.toString();', examples: [{ title: '字符串拼接', code: 'StringBuilder sb = new StringBuilder();\nfor (int i = 0; i < 100; i++) sb.append(i);\nString s = sb.toString();\nsb.reverse();\nsb.deleteCharAt(0);\nsb.insert(0, "x");' }], complexity: 'append 均摊 O(1)', notes: 'StringBuffer 是线程安全版但更慢。StringBuilder 非线程安全，性能更好。', leetcode_tips: '循环拼接字符串务必用 StringBuilder，避免 O(n²)。reverse() 方便字符串反转。', see_also: ['string'] })
add({ id: 'arrays', name: 'Arrays', category: '工具类', language: 'java', full_name: 'java.util.Arrays', signature: 'Arrays', signatures: ['java.util.Arrays'], description: '数组操作工具类，提供排序、二分查找、填充、拷贝、转 List 等静态方法。', example: 'int[] arr = {3,1,2};\nArrays.sort(arr);\nint i = Arrays.binarySearch(arr, 2);', examples: [{ title: '常用方法', code: 'int[] a = {3,1,2};\nArrays.sort(a);\nint idx = Arrays.binarySearch(a, 2);\nint[] copy = Arrays.copyOf(a, 5);\nArrays.fill(a, 0);\nString s = Arrays.toString(a);\nList<Integer> list = Arrays.asList(1,2,3);' }, { title: '二维排序', code: 'int[][] intervals = {{1,3},{2,6},{8,10}};\nArrays.sort(intervals, (a,b) -> a[0] - a[1]);' }], complexity: 'sort O(n log n), binarySearch O(log n)', notes: 'binarySearch 需要先排序。asList 返回固定大小列表，不支持 add/remove。', leetcode_tips: '数组排序、拷贝、toString 调试时非常常用。', see_also: ['collections', 'arraylist'] })
add({ id: 'collections', name: 'Collections', category: '工具类', language: 'java', full_name: 'java.util.Collections', signature: 'Collections', signatures: ['java.util.Collections'], description: '集合工具类，提供排序、反转、洗牌、不可变包装等静态方法。', example: 'List<Integer> list = new ArrayList<>(Arrays.asList(3,1,2));\nCollections.sort(list);', examples: [{ title: '常用方法', code: 'List<Integer> list = new ArrayList<>(List.of(3,1,2));\nCollections.sort(list);\nCollections.reverse(list);\nCollections.shuffle(list);\nint mx = Collections.max(list);\nint mn = Collections.min(list);\nCollections.frequency(list, 1);\nCollections.swap(list, 0, 1);' }], complexity: 'sort O(n log n)', notes: 'Collections.sort 在 Java 8+ 使用 TimSort（稳定排序）。', leetcode_tips: 'Collections.reverse 反转 List。Collections.singletonList 创建单元素列表。', see_also: ['arrays', 'comparator'] })
add({ id: 'optional_java', name: 'Optional', category: '工具类', language: 'java', full_name: 'java.util.Optional<T>', signature: 'Optional<T>', signatures: ['Optional<T> (Java 8+)'], description: '容器对象，可能包含也可能不包含非 null 值。函数式处理空值。', example: 'Optional<String> opt = Optional.of("hello");\nopt.ifPresent(s -> System.out.println(s));', examples: [{ title: '函数式用法', code: 'Optional<String> opt = Optional.ofNullable(getValue());\nString result = opt\n  .filter(s -> s.length() > 3)\n  .map(String::toUpperCase)\n  .orElse("default");' }], complexity: '', notes: '不要用 Optional 作为字段类型或方法参数。orElse 和 orElseGet 的区别：orElse 总是求值。', leetcode_tips: '避免返回 null，用 Optional 表示可能缺失的值。', see_also: ['stream', 'optional'] })
add({ id: 'stream', name: 'Stream', category: '函数式', language: 'java', full_name: 'java.util.stream.Stream<T>', signature: 'Stream<T>', signatures: ['Stream<T> (Java 8+)', 'IntStream / LongStream / DoubleStream'], description: '支持函数式操作（map/filter/reduce）的元素序列。不存储数据，可链式调用。', example: 'List<Integer> nums = Arrays.asList(1,2,3,4);\nint sum = nums.stream().filter(n -> n % 2 == 0).mapToInt(n -> n).sum();', examples: [{ title: '常用操作', code: 'list.stream()\n  .filter(x -> x > 0)\n  .map(String::valueOf)\n  .sorted()\n  .collect(Collectors.toList());' }, { title: 'IntStream 范围', code: 'IntStream.range(0, 10).forEach(System.out::println);\nIntStream.rangeClosed(1, 5).sum();' }], complexity: '', notes: 'Stream 是惰性求值，终端操作执行后才计算。不可重用。parallelStream 并行处理。', leetcode_tips: '数组/列表的快速过滤、映射、统计。Collectors.groupingBy 分组很实用。', see_also: ['collectors', 'optional_java'] })
add({ id: 'collectors', name: 'Collectors', category: '函数式', language: 'java', full_name: 'java.util.stream.Collectors', signature: 'Collectors', signatures: ['java.util.stream.Collectors (Java 8+)'], description: 'Stream 的终端收集工具，将流元素累积到 List/Set/Map 等容器。', example: 'List<String> list = stream.collect(Collectors.toList());', examples: [{ title: '分组', code: 'Map<Integer, List<String>> byLen = strings.stream()\n  .collect(Collectors.groupingBy(String::length));' }, { title: 'joining', code: 'String s = list.stream().collect(Collectors.joining(", "));' }], complexity: '', notes: 'toMap 需处理 key 冲突。groupingBy 默认返回 HashMap。', leetcode_tips: 'groupingBy 按条件分组，partitioningBy 二分分区，joining 拼接字符串。', see_also: ['stream', 'arrays'] })
add({ id: 'priorityqueue_java', name: 'PriorityQueue', category: '队列', language: 'java', full_name: 'java.util.PriorityQueue<E>', signature: 'PriorityQueue<E>', signatures: ['PriorityQueue<E>'], description: '基于最小堆（默认）的优先级队列。支持 Comparator 自定义排序。', example: 'PriorityQueue<Integer> pq = new PriorityQueue<>();\npq.add(3);\npq.peek();\npq.poll();', examples: [{ title: '最大堆', code: 'PriorityQueue<Integer> maxPq = new PriorityQueue<>(Collections.reverseOrder());\nmaxPq.add(1); maxPq.add(3); maxPq.add(2);' }, { title: '自定义优先级', code: 'PriorityQueue<int[]> pq = new PriorityQueue<>((a,b) -> a[0] - a[1]);\npq.add(new int[]{5,1});' }], complexity: 'offer/poll O(log n), peek O(1)', notes: '迭代器不保证顺序。默认最小堆（小的先出队）。', leetcode_tips: 'Top K、合并 K 个有序链表、Dijkstra 算法。', see_also: ['collections', 'arrays'] })
add({ id: 'arraydeque', name: 'ArrayDeque', category: '队列', language: 'java', full_name: 'java.util.ArrayDeque<E>', signature: 'ArrayDeque<E>', signatures: ['ArrayDeque<E>'], description: '可变大小双端队列，可作栈或队列使用。比 Stack 和 LinkedList 更高效。', example: 'ArrayDeque<Integer> stack = new ArrayDeque<>();\nstack.push(1);\nstack.pop();', examples: [{ title: '栈', code: 'ArrayDeque<String> stack = new ArrayDeque<>();\nstack.push("a"); stack.push("b");\nstack.pop(); // "b"' }, { title: '队列', code: 'ArrayDeque<Integer> q = new ArrayDeque<>();\nq.offer(1); q.offer(2);\nq.poll(); // 1' }], complexity: 'O(1) 所有操作', notes: 'ArrayDeque 比 Stack（遗留类）更快。不允许多个 null 元素。', leetcode_tips: '栈操作推荐用 ArrayDeque 替代 Stack。滑动窗口最大值用 ArrayDeque 存下标。', see_also: ['linkedlist', 'stack'] })
add({ id: 'comparator', name: 'Comparator', category: '工具类', language: 'java', full_name: 'java.util.Comparator<T>', signature: 'Comparator<T>', signatures: ['Comparator<T>'], description: '比较函数接口，定义对象排序规则。可用 lambda 或方法引用实现。', example: 'Comparator<Integer> cmp = (a, b) -> b - a; // 降序', examples: [{ title: '链式比较', code: 'Comparator<Person> cmp = Comparator\n  .comparing(Person::getLastName)\n  .thenComparing(Person::getFirstName);\nCollections.sort(people, cmp);' }], returns: 'int：负/零/正', complexity: '', notes: 'compare(a,b) 返回负值表示 a < b。必须满足传递性、反对称性。', leetcode_tips: '自定义排序规则时大量使用。comparingInt 避免自动装箱。', see_also: ['collections', 'arrays', 'priorityqueue_java'] })
// === Python ===
add({ id: 'py_list', name: 'list', category: '内置类型', language: 'python', full_name: 'list', signature: 'list([iterable])', signatures: ['list([iterable])'], description: '可变序列，可存放任意类型元素。动态数组，尾部插入 O(1)，中间插入 O(n)。', example: 'lst = [1, 2, 3]\nlst.append(4)\nlst.pop()', examples: [{ title: '推导式', code: 'squares = [x*x for x in range(10)]\neven = [x for x in lst if x % 2 == 0]' }, { title: '常用方法', code: 'lst = [3,1,2]\nlst.sort()\nlst.reverse()\nlst.append(4)\nlst.pop()\nlst.insert(0, 0)\nlst.remove(1)\nlst.count(2)\nlst.index(3)' }], complexity: '索引 O(1), append 均摊 O(1), 插入/删除 O(n)', notes: 'list.sort() 原地排序（Timsort，稳定），sorted(lst) 返回新列表。', leetcode_tips: 'list comprehension 比手动 for 循环快。sort(key=...) 自定义排序键。', see_also: ['tuple', 'deque_py', 'py_range'] })
add({ id: 'py_dict', name: 'dict', category: '内置类型', language: 'python', full_name: 'dict', signature: 'dict(**kwargs) / dict(iterable) / {key: value}', signatures: ['dict(**kwargs)', 'dict(iterable)', '{key: value}'], description: '字典，键值对映射。Python 3.7+ 保持插入顺序。平均 O(1) 操作。', example: 'd = {"a": 1, "b": 2}\nd.get("a")\nd["c"] = 3', examples: [{ title: '计数', code: 'd = {}\nfor c in s:\n  d[c] = d.get(c, 0) + 1\n# or use collections.Counter' }, { title: '字典推导', code: 'squares = {x: x*x for x in range(5)}\n# {0:0, 1:1, 2:4, 3:9, 4:16}' }], complexity: '平均 O(1)', notes: 'Python 3.6 起 dict 使用紧凑表示节省内存。keys()/values()/items() 返回视图。', leetcode_tips: '哈希表计数、缓存中间结果。setdefault 方法可简化初始化。', see_also: ['defaultdict', 'counter', 'py_set'] })
add({ id: 'py_set', name: 'set', category: '内置类型', language: 'python', full_name: 'set', signature: 'set([iterable])', signatures: ['set([iterable])'], description: '无序集合，元素唯一。平均 O(1) 成员检测。支持 & | - ^ 运算。', example: 's = {1, 2, 3}\ns.add(4)\ns.remove(2)', examples: [{ title: '集合运算', code: 'a = {1,2,3}\nb = {2,3,4}\na & b  # {2,3} 交集\na | b  # {1,2,3,4} 并集\na - b  # {1} 差集\na ^ b  # {1,4} 对称差' }, { title: '去重', code: 'unique = list(set([1,2,2,3]))\n# [1,2,3] 注意顺序不保证' }], complexity: '平均 O(1)', notes: '元素必须可哈希（hashable）。frozenset 是不可变版本。', leetcode_tips: '快速去重、成员检查、集合运算（如共同好友）。', see_also: ['py_list', 'py_dict', 'counter'] })
add({ id: 'py_str', name: 'str', category: '内置类型', language: 'python', full_name: 'str', signature: 'str(object="")', signatures: ['str(object="")'], description: '不可变的 Unicode 字符串序列。支持切片、查找、替换等丰富操作。', example: 's = "hello"\ns.upper()\ns[0:3]\ns.find("ll")', examples: [{ title: '常用方法', code: 's = "LeetCode"\ns.lower()\ns.upper()\ns.isdigit()\ns.isalpha()\ns.split(",")\ns.join(["a","b"])\ns.strip()\ns.replace("e", "a")\ns.startswith("Lee")\ns.count("e")' }, { title: '切片与反转', code: 's = "abcdef"\ns[::-1]  # "fedcba" 反转\ns[::2]   # "ace" 隔一取一\ns[1:4]   # "bcd"' }], complexity: '索引 O(1), 查找 O(n), 切片 O(k)', notes: '字符串不可变，所有方法返回新字符串。join 比 + 拼接更高效。', leetcode_tips: 's[::-1] 反转字符串。split/join 处理单词拆分。切片左闭右开。', see_also: ['py_list', 'tuple', 'enumerate_zip'] })
add({ id: 'py_tuple', name: 'tuple', category: '内置类型', language: 'python', full_name: 'tuple', signature: 'tuple([iterable])', signatures: ['tuple([iterable])'], description: '不可变序列，可包含任意类型。适合作为字典键或打包多个返回值。', example: 't = (1, 2, 3)\na, b, c = t\nx, y = y, x  # swap via tuple', examples: [{ title: '解包', code: 'point = (10, 20)\nx, y = point\ndef min_max(lst):\n  return min(lst), max(lst)' }], complexity: '索引 O(1)', notes: '单元素元组需加逗号: (1,)。namedtuple 给元组元素命名。', leetcode_tips: '用作哈希表的键（如 (i,j) 坐标）。多个返回值打包。', see_also: ['py_list', 'py_str', 'namedtuple'] })
add({ id: 'py_range', name: 'range', category: '内置类型', language: 'python', full_name: 'range', signature: 'range(stop) / range(start, stop, step)', signatures: ['range(stop)', 'range(start, stop, step)'], description: '不可变数值序列，延迟计算（不一次性生成所有值）。内存友好。', example: 'for i in range(10): ...\nlist(range(0, 10, 2))  # [0,2,4,6,8]', examples: [{ title: '反向遍历', code: 'for i in range(10, 0, -1):\n  print(i)\n# 10, 9, 8, ..., 1' }], complexity: 'O(1) 生成, O(n) 遍历', notes: 'range 是惰性的，适合大数据范围。in 操作也是 O(1)。', leetcode_tips: '倒序遍历 range(n-1, -1, -1)。range(len(arr)) 不如 enumerate。', see_also: ['py_list', 'enumerate_zip'] })
add({ id: 'enumerate_zip', name: 'enumerate / zip', category: '内置函数', language: 'python', full_name: 'enumerate / zip', signature: 'enumerate(iterable, start=0) / zip(*iterables)', signatures: ['enumerate(iterable, start=0)', 'zip(*iterables)'], description: 'enumerate 返回索引-元素对。zip 并行聚合多个可迭代对象。', example: 'for i, char in enumerate("abc"):\n  print(i, char)', examples: [{ title: 'enumerate', code: 'for idx, val in enumerate(["a","b","c"], start=1):\n  print(idx, val)' }, { title: 'zip', code: 'keys = ["a","b","c"]\nvals = [1,2,3]\nd = dict(zip(keys, vals))\n# {"a":1, "b":2, "c":3}\nfor k, v in zip(keys, vals): ...' }], returns: '迭代器', complexity: 'O(1) 返回迭代器, 遍历 O(n)', notes: 'zip 在最短输入耗尽时停止。zip_longest 在 itertools 中。', leetcode_tips: '同时遍历索引和值用 enumerate。同时遍历多个列表用 zip。', see_also: ['py_range', 'map_filter', 'any_all'] })
add({ id: 'any_all', name: 'any / all', category: '内置函数', language: 'python', full_name: 'any / all', signature: 'any(iterable) / all(iterable)', signatures: ['any(iterable)', 'all(iterable)'], description: 'any 可迭代对象中任一为真返回 True。all 所有为真返回 True。短路求值。', example: 'any(x > 5 for x in nums)\nall(x > 0 for x in nums)', examples: [{ title: '条件检查', code: 'nums = [1,2,3,4,5]\nhas_even = any(x % 2 == 0 for x in nums)  # True\nall_positive = all(x > 0 for x in nums)    # True' }], returns: 'bool', complexity: '短路，最坏 O(n)', notes: '空可迭代对象：any 返回 False，all 返回 True。', leetcode_tips: '条件判断、边界检查（如棋盘、矩阵的合法性）。', see_also: ['map_filter', 'enumerate_zip'] })
add({ id: 'sorted_reversed', name: 'sorted / reversed', category: '内置函数', language: 'python', full_name: 'sorted / reversed', signature: 'sorted(iterable, key=None, reverse=False) / reversed(seq)', signatures: ['sorted(iterable, key=None, reverse=False)', 'reversed(seq)'], description: 'sorted 返回排序后的新列表。reversed 返回反向迭代器。', example: 'sorted([3,1,2])  # [1,2,3]\nlist(reversed([1,2,3]))  # [3,2,1]', examples: [{ title: 'sorted 自定义', code: 'students = [("Alice", 25), ("Bob", 20)]\nsorted_by_age = sorted(students, key=lambda x: x[1])\n# [("Bob",20), ("Alice",25)]' }], returns: 'sorted 返回 list，reversed 返回迭代器', complexity: 'sorted O(n log n), reversed O(1)', notes: 'sorted 返回新列表，不修改原对象。reversed 返回迭代器，需 list() 展开。', leetcode_tips: 'sorted 配合 key 灵活排序。reversed 比 [::-1] 更省内存。', see_also: ['py_list', 'py_range', 'enumerate_zip'] })
add({ id: 'deque_py', name: 'collections.deque', category: 'collections', language: 'python', full_name: 'collections.deque', signature: 'collections.deque([iterable], maxlen=None)', signatures: ['collections.deque([iterable], maxlen=None)'], description: '双端队列，两端 O(1) 插入/删除。支持 maxlen 限制长度。', example: 'from collections import deque\ndq = deque([1,2,3])\ndq.append(4)\ndq.popleft()', examples: [{ title: '队列', code: 'from collections import deque\nq = deque()\nq.append(1)\nq.popleft()' }, { title: '定长滑动窗口', code: 'window = deque(maxlen=3)\nfor x in data:\n  window.append(x)  # 自动移除超出的左端元素' }], complexity: 'O(1) 两端操作', notes: '线程安全的头尾操作。maxlen 超过容量时自动丢弃左端元素。', leetcode_tips: 'BFS 队列、滑动窗口、回文检查。比 list 做队列快（list.pop(0) 是 O(n)）。', see_also: ['py_list', 'defaultdict', 'heapq'] })
add({ id: 'defaultdict', name: 'defaultdict', category: 'collections', language: 'python', full_name: 'collections.defaultdict', signature: 'collections.defaultdict(default_factory)', signatures: ['collections.defaultdict(default_factory)'], description: '带默认值的字典。访问不存在的键时，自动调用 default_factory 生成默认值。', example: 'from collections import defaultdict\nd = defaultdict(int)\nd["a"] += 1  # 无需先初始化', examples: [{ title: '计数', code: 'freq = defaultdict(int)\nfor c in s:\n  freq[c] += 1' }, { title: '分组', code: 'groups = defaultdict(list)\nfor name, score in data:\n  groups[name].append(score)' }], complexity: '平均 O(1)', notes: 'default_factory 可以是 int/list/set/dict 等。lambda 可自定义。', leetcode_tips: '分组、计数、邻接表构建时非常方便，避免手动检查键是否存在。', see_also: ['py_dict', 'counter', 'deque_py'] })
add({ id: 'counter', name: 'Counter', category: 'collections', language: 'python', full_name: 'collections.Counter', signature: 'collections.Counter([iterable])', signatures: ['collections.Counter([iterable])'], description: '计数哈希表，继承 dict。统计可哈希对象出现次数。', example: 'from collections import Counter\ncnt = Counter("aabbbc")\nprint(cnt["a"])  # 2\nprint(cnt.most_common(2))', examples: [{ title: '常用操作', code: 'cnt = Counter("leetcode")\ncnt["e"]  # 2\ncnt.most_common(2)  # [("e",2), ("l",1)]\nlist(cnt.elements())\ncnt2 = Counter("leet")\ncnt - cnt2  # 差值计数' }], complexity: '构建 O(n)', notes: 'most_common 使用堆排序，O(n log k)。update 可追加计数。subtract 减去计数。', leetcode_tips: '字符/单词频次统计、Anagram 判断、找出出现次数前 k 的元素。', see_also: ['py_dict', 'defaultdict', 'heapq'] })
add({ id: 'namedtuple', name: 'namedtuple', category: 'collections', language: 'python', full_name: 'collections.namedtuple', signature: 'namedtuple(typename, field_names)', signatures: ['namedtuple(typename, field_names)'], description: '命名元组工厂函数，创建带字段名的轻量级不可变类。比普通类更省内存。', example: 'from collections import namedtuple\nPoint = namedtuple("Point", ["x", "y"])\np = Point(1, 2)\np.x + p.y', examples: [{ title: '定义与使用', code: 'Student = namedtuple("Student", ["name", "age", "grade"])\ns = Student("Alice", 20, "A")\ns.name  # "Alice"\nname, age, grade = s  # 支持解包' }], returns: 'namedtuple 类', complexity: '', notes: '字段也可通过下标访问（因继承 tuple）。_replace 方法创建新实例。_asdict 转字典。', leetcode_tips: '表示坐标、权重边等不可变数据结构。比 dict 省内存。', see_also: ['py_tuple', 'dataclasses'] })
add({ id: 'heapq', name: 'heapq', category: '算法', language: 'python', full_name: 'heapq (堆队列)', signature: 'heapq.heappush(heap, item) / heapq.heappop(heap)', signatures: ['heapq.heappush(heap, item)', 'heapq.heappop(heap)', 'heapq.heapify(x)', 'heapq.nlargest(n, iterable)', 'heapq.nsmallest(n, iterable)'], description: '最小堆实现。heapify 将列表转为堆（O(n)），heappush/heappop O(log n)。', example: 'import heapq\nheap = [3, 1, 2]\nheapq.heapify(heap)\nsmallest = heapq.heappop(heap)  # 1', examples: [{ title: '最大堆模拟', code: 'import heapq\nheap = []\nfor x in [1,2,3]:\n  heapq.heappush(heap, -x)\nmx = -heapq.heappop(heap)  # 3' }, { title: 'Top K', code: 'data = [3,1,4,1,5,9,2,6]\nlargest = heapq.nlargest(3, data)  # [9,6,5]\nsmallest = heapq.nsmallest(3, data)  # [1,1,2]' }], complexity: 'heappush/heappop O(log n), heapify O(n)', notes: '默认最小堆。最大堆通过存储负值实现。', leetcode_tips: 'Top K 问题（解法 2）、合并有序链表、Dijkstra 最短路径。', see_also: ['priorityqueue_java', 'priority_queue', 'counter'] })
add({ id: 'bisect', name: 'bisect', category: '算法', language: 'python', full_name: 'bisect (二分查找)', signature: 'bisect.bisect_left(a, x) / bisect.bisect_right(a, x)', signatures: ['bisect.bisect_left(a, x, lo=0, hi=len(a))', 'bisect.bisect_right(a, x, lo=0, hi=len(a))', 'bisect.insort(a, x, lo=0, hi=len(a))'], description: '对有序序列的二分查找。bisect_left 返回插入点（左侧），bisect_right 返回插入点（右侧）。', example: 'import bisect\na = [1,2,2,3]\npos = bisect.bisect_left(a, 2)  # 1\npos = bisect.bisect_right(a, 2) # 3', examples: [{ title: '二分查找', code: 'arr = [1,2,4,5]\nidx = bisect.bisect_left(arr, 3)  # 2 (插入位置)\ndef exists(arr, x):\n  i = bisect.bisect_left(arr, x)\n  return i < len(arr) and arr[i] == x' }], complexity: 'O(log n)', notes: 'bisect_left 找第一个 >= x，bisect_right 找第一个 > x。insort 在插入点插入。', leetcode_tips: '最长递增子序列（耐心排序）、二维二分、按值搜索。', see_also: ['lower_upper_bound', 'sorted_reversed'] })
add({ id: 'itertools', name: 'itertools', category: '算法', language: 'python', full_name: 'itertools (迭代器工具)', signature: 'itertools.product / permutations / combinations / accumulate', signatures: ['itertools.product(*iterables, repeat=1)', 'itertools.permutations(iterable, r=None)', 'itertools.combinations(iterable, r)', 'itertools.combinations_with_replacement(iterable, r)', 'itertools.accumulate(iterable, func=operator.add)'], description: '高效的迭代器函数库，延迟生成数据，节省内存。', example: 'from itertools import product, permutations, combinations\nlist(product("AB", repeat=2))', examples: [{ title: '排列组合', code: 'from itertools import *\n# 笛卡尔积\nlist(product([1,2], "AB"))\n# 排列\nlist(permutations([1,2,3], 2))\n# 组合\nlist(combinations([1,2,3], 2))' }, { title: 'accumulate', code: 'list(accumulate([1,2,3,4]))  # [1,3,6,10] 前缀和\nlist(accumulate([1,2,3], lambda x,y: x*y))  # [1,2,6]' }], complexity: '遍历 O(n!) 取决于具体操作', notes: 'itertools 返回迭代器，需 list() 展开。组合数大时注意内存。', leetcode_tips: 'product 做嵌套循环（N 皇后），combinations 找子集，accumulate 前缀和。', see_also: ['map_filter', 'enumerate_zip'] })
add({ id: 'functools', name: 'functools', category: '函数式', language: 'python', full_name: 'functools (函数工具)', signature: 'functools.lru_cache / functools.reduce / functools.cmp_to_key', signatures: ['functools.lru_cache(maxsize=128)', 'functools.reduce(function, iterable, initializer)', 'functools.cmp_to_key(func)'], description: '高阶函数工具。lru_cache 缓存函数结果（DP 记忆化），reduce 逐元素累积。', example: 'from functools import lru_cache\n@lru_cache(maxsize=None)\ndef fib(n):\n  if n < 2: return n\n  return fib(n-1) + fib(n-2)', examples: [{ title: 'LRU Cache 记忆化', code: 'from functools import lru_cache\n@lru_cache(maxsize=None)\ndef dfs(i, j):\n  if i >= m or j >= n: return 0\n  return max(dfs(i+1,j), dfs(i,j+1)) + grid[i][j]' }, { title: 'reduce', code: 'from functools import reduce\nnums = [1,2,3,4]\nprod = reduce(lambda x,y: x*y, nums)  # 24\nfrom operator import mul\nprod = reduce(mul, nums, 1)' }], complexity: '', notes: 'lru_cache 默认 maxsize=128，设为 None 无限缓存。reduce 相当于 fold。', leetcode_tips: 'DFS DP 记忆化用 @lru_cache 极其方便。', see_also: ['itertools', 'map_filter'] })
add({ id: 'map_filter', name: 'map / filter', category: '内置函数', language: 'python', full_name: 'map / filter', signature: 'map(func, *iterables) / filter(func, iterable)', signatures: ['map(func, *iterables)', 'filter(func, iterable)'], description: 'map 对可迭代对象每个元素应用函数。filter 过滤满足条件的元素。均返回迭代器。', example: 'list(map(str, [1,2,3]))\nlist(filter(lambda x: x > 0, [-1, 0, 1]))', examples: [{ title: 'map', code: 'nums = [1,2,3]\ndoubled = list(map(lambda x: x*2, nums))\n# list comprehension 通常更 Pythonic:\ndoubled = [x*2 for x in nums]' }, { title: 'filter', code: 'nums = [1,2,3,4,5]\nevens = list(filter(lambda x: x % 2 == 0, nums))\n# [2,4]\n# list comprehension:\nevens = [x for x in nums if x % 2 == 0]' }], complexity: 'O(1) 返回迭代器', notes: 'Python 中 list comprehension 通常比 map/filter 更清晰。', leetcode_tips: '列表推导式通常比 map/filter 更推荐。map 搭配多个可迭代对象时有用。', see_also: ['enumerate_zip', 'any_all', 'py_list'] })

console.log('Total:', entries.length)

let result = "import type { ApiEntry } from '../types'\n\nexport const apiData: ApiEntry[] = [\n"
for (const e of entries) result += entry(e) + ',\n'
result += ']\n'
writeFileSync('src/data/stl.ts', result, 'utf8')
console.log('Written!')
